export const DICT_FR_PAGES: Record<string, string> = {
  "IA para potenciar tu PyME": "L'IA pour booster ta PME",
  "La inteligencia artificial creada para las MiPyMEs de Latinoamérica": "L'intelligence artificielle créée pour les TPE et PME d'Amérique latine",
  "Logra te ayuda a ahorrar tiempo y ser más eficiente para potencializar tu negocio.": "Logra t'aide à gagner du temps et à être plus efficace pour booster ton entreprise.",
  "Probar sin costo": "Essayer gratuitement",
  "4000+ MiPyMES confían en nosotros": "4000+ TPE et PME nous font confiance",
  "Ana Maria Ruge": "Ana Maria Ruge",
  "Efecto": "Efecto",
  "Cindy Colorado": "Cindy Colorado",
  "Dobladora y cortadora": "Dobladora y cortadora",
  "Oscar Gonzalez": "Oscar Gonzalez",
  "Inseprosas": "Inseprosas",
  "Ximena Camelo": "Ximena Camelo",
  "Mentor Go": "Mentor Go",
  "Carlos Chaves": "Carlos Chaves",
  "Datagrafía": "Datagrafía",
  "Una plataforma súper simple, hecha para empresarios que empiezan con el uso de la tecnología y quieren resultados inmediatos.": "Une plateforme ultra simple, conçue pour les entrepreneurs qui débutent avec la technologie et veulent des résultats immédiats.",
  "¿Cómo Logra te da más control, más enfoque y más eficiencia en tu día a día?": "Comment Logra te donne plus de contrôle, plus de focus et plus d'efficacité au quotidien ?",
  "Ahorro de tiempo": "Gain de temps",
  "Ejecuta tareas en segundos en lugar de horas.": "Exécute tes tâches en quelques secondes au lieu de plusieurs heures.",
  "Objetivos claros": "Objectifs clairs",
  "Define tus metas cada semana y logra más resultados.": "Définis tes objectifs chaque semaine et obtiens plus de résultats.",
  "Eficiencia operativa": "Efficacité opérationnelle",
  "Construye procesos y aclara tu estrategia paso a paso.": "Construis tes processus et clarifie ta stratégie pas à pas.",
  "Progreso transparente": "Progrès transparent",
  "Mide el impacto de adoptar inteligencia artificial en equipo.": "Mesure l'impact de l'adoption de l'intelligence artificielle en équipe.",
  "¿Cómo funciona?": "Comment ça marche ?",
  "Chat de inteligencia artificial": "Chat d'intelligence artificielle",
  "Conversa con tu inteligencia artificial para ejecutar tareas, tácticas o simplemente obtener apoyo, planes o ideas según tu necesidad.": "Discute avec ton intelligence artificielle pour exécuter des tâches, des tactiques ou simplement obtenir du soutien, des plans ou des idées selon tes besoins.",
  "Organizador de Tareas": "Organisateur de tâches",
  "Organiza tus tareas y metas en un Tablero que te permite asignar, dar seguimiento y filtrar todo lo importante de tu semana.": "Organise tes tâches et objectifs dans un Tableau qui te permet d'assigner, suivre et filtrer tout ce qui compte dans ta semaine.",
  "Formatos para tu Estrategia": "Modèles pour ta stratégie",
  "Entrena a tu inteligencia artificial con formatos inteligentes para que conozca a tu empresa mejor que cualquier Asesor y te de respuestas súper personalizadas.": "Entraîne ton intelligence artificielle avec des modèles intelligents pour qu'elle connaisse ton entreprise mieux que n'importe quel conseiller et te donne des réponses ultra personnalisées.",
  "Progreso semanal": "Progrès hebdomadaire",
  "Mide las tareas que completas y el uso de inteligencia artificial de tu equipo para entender el tiempo ahorrado y la eficiencia de tu equipo.": "Mesure les tâches accomplies et l'usage de l'intelligence artificielle par ton équipe pour comprendre le temps gagné et son efficacité.",
  "Urgencia": "Urgence",
  "2 de cada 3 PyMEs fracasan en los primeros 5 años.": "2 PME sur 3 échouent dans les 5 premières années.",
  "¿De qué lado quieres estar?": "De quel côté veux-tu être ?",
  "+5h pérdidas por empleado cada semana": "+5h perdues par employé chaque semaine",
  "Hacen tareas repetitivas e innecesarias, por ser desorganizados. Si les sobre tiempo, super. Si no, mejor ahórralo.": "Ils font des tâches répétitives et inutiles, faute d'organisation. S'il te reste du temps, tant mieux. Sinon, mieux vaut l'économiser.",
  "+70% siguen operando en papel y Excel": "+70% fonctionnent encore sur papier et Excel",
  "La ineficiencia y falta de digitalización les cuesta. Más errores, más costos y menos oportunidades: la peor manera de crecer.": "L'inefficacité et le manque de digitalisation leur coûtent cher. Plus d'erreurs, plus de coûts et moins d'opportunités : la pire façon de grandir.",
  "90% toman decisiones con emociones y sin data": "90% décident à l'émotion, sans données",
  "Decidir sin analizar números es muy arriesgado. La intuición es buena para jugar en el casino, pero no para dirigir un negocio.": "Décider sans analyser les chiffres est très risqué. L'intuition, c'est bien pour jouer au casino, pas pour diriger une entreprise.",
  "Beneficios": "Avantages",
  "Las MiPyMEs que adoptan inteligencia artificial": "Les TPE et PME qui adoptent l'intelligence artificielle",
  "tienen": "ont",
  "40% más probabilidad de crecer.": "40% de chances en plus de grandir.",
  "La IA trabaja por ti": "L'IA travaille pour toi",
  "Enfócate en lo importante": "Concentre-toi sur l'essentiel",
  "Decides con más seguridad": "Tu décides avec plus d'assurance",
  "La inteligencia artificial trabaja por ti": "L'intelligence artificielle travaille pour toi",
  "Ejecuta tus tareas repetitivas en segundos. Te crea planes de acción y procesos para avanzar más rápido.": "Elle exécute tes tâches répétitives en quelques secondes. Elle te crée des plans d'action et des processus pour avancer plus vite.",
  "Nuestros Planes": "Nos plans",
  "Diseñado para crecer en Equipo.": "Conçu pour grandir en équipe.",
  "Plan Básico": "Plan Basique",
  "Micro Empresarios": "Micro-entrepreneurs",
  "$9 USD/mes": "$9 USD/mois",
  "Inteligencia artificial 100% personalizada a tu negocio": "Intelligence artificielle 100% personnalisée pour ton entreprise",
  "20 Chats, tareas y tácticas con IA": "20 chats, tâches et tactiques avec l'IA",
  "Organización y seguimiento de Tareas cada semana": "Organisation et suivi des tâches chaque semaine",
  "Plan Pro": "Plan Pro",
  "Equipo de 3": "Équipe de 3",
  "$14 USD/mes": "$14 USD/mois",
  "Todo lo incluido en el Plan Gratuito": "Tout ce qui est inclus dans le Plan Gratuit",
  "Acceso a 2 miembros de tu equipo": "Accès pour 2 membres de ton équipe",
  "Chats, tareas y tácticas con IA ilimitados": "Chats, tâches et tactiques illimités avec l'IA",
  "Plan Premium": "Plan Premium",
  "Todo tu equipo": "Toute ton équipe",
  "$25 USD/mes": "$25 USD/mois",
  "Todo lo incluido en el Plan Pro": "Tout ce qui est inclus dans le Plan Pro",
  "Miembros de equipo ilimitado": "Membres d'équipe illimités",
  "Asesoría de 30 minutos y soporte prioritario": "Session conseil de 30 minutes et support prioritaire",
  "Oportunidad": "Opportunité",
  "4000+ empresarios ya usan Logra para mejorar cada día": "4000+ entrepreneurs utilisent déjà Logra pour s'améliorer chaque jour",
  "Pruébalo sin costo hoy y obtén resultados de inmediato.": "Essaie-le gratuitement aujourd'hui et obtiens des résultats immédiats.",
  "Crea una cuenta": "Crée un compte",
  "IA para potenciar tu red de PyMEs": "L'IA pour booster ton réseau de PME",
  "Capacita tus MiPyMEs y dales acceso a la inteligencia artificial": "Forme tes TPE et PME et donne-leur accès à l'intelligence artificielle",
  "Logra es una solución llave en mano que impulsa a tus afiliados y te da acceso a datos increíbles para entenderlos mejor.": "Logra est une solution clé en main qui propulse tes affiliés et te donne accès à des données incroyables pour mieux les comprendre.",
  "Agenda una Demo": "Réserve une démo",
  "Trabajamos con instituciones líderes en Colombia y nuestro servicio está disponible en toda América Latina.": "Nous travaillons avec des institutions de premier plan en Colombie et notre service est disponible dans toute l'Amérique latine.",
  "Cómo funciona": "Comment ça marche",
  "Combinamos Talleres virtuales, una plataforma 100% hecha para MiPyMEs de la región y un Dashboard de datos para tu institución.": "Nous combinons des ateliers virtuels, une plateforme 100% pensée pour les TPE et PME de la région et un dashboard de données pour ton institution.",
  "Diseñamos una experiencia completa que te permite apoyar la mayor cantidad de negocios afiliados de tu red, al menor costo posible.": "Nous avons conçu une expérience complète qui te permet de soutenir un maximum d'entreprises affiliées de ton réseau, au coût le plus bas possible.",
  "Talleres virtuales de capacitación": "Ateliers virtuels de formation",
  "Son sesiones de 60 minutos que llevamos cada semana para guiar a las PyMEs a empezar a utilizar la inteligencia artificial para organizar sus tareas, ejecutarlas en segundos y medir el tiempo ahorrado.": "Des sessions de 60 minutes animées chaque semaine pour guider les PME dans leurs premiers pas avec l'intelligence artificielle : organiser leurs tâches, les exécuter en quelques secondes et mesurer le temps gagné.",
  "Análisis de datos en tiempo real": "Analyse de données en temps réel",
  "Accedes a un Dashboard analítico que te permite analizar datos de todas tus MiPyMEs afiliadas que utilizan la plataforma. Entiendes mejor sus retos y cómo usan la IA, para diseñar soluciones más adecuadas.": "Tu accèdes à un dashboard analytique pour analyser les données de toutes tes TPE et PME affiliées qui utilisent la plateforme. Tu comprends mieux leurs défis et leur usage de l'IA, pour concevoir des solutions plus adaptées.",
  "Modelo ganar/ganar para todos": "Un modèle gagnant-gagnant pour tous",
  "Por ser invitadas por ti, tus empresas afiliadas acceden a la versión gratuita de forma permanente. Si contratan la versión Pro, les damos un descuento por ser de tu red y a ti te entregamos un porcentaje.": "Invitées par toi, tes entreprises affiliées accèdent à la version gratuite de façon permanente. Si elles passent à la version Pro, elles reçoivent une remise réservée à ton réseau et tu touches un pourcentage.",
  "Los programas e iniciativas de apoyo que despliegan para apoyar a sus MiPyMEs": "Les programmes et initiatives déployés pour soutenir leurs TPE et PME",
  "tienen ciertos limitantes.": "ont certaines limites.",
  "No son escalables": "Ils ne sont pas scalables",
  "Los cursos, asesorías y talleres están limitados a pocas empresas. El impacto es limitado por falta de tecnología.": "Les cours, accompagnements et ateliers sont limités à quelques entreprises. L'impact est restreint par le manque de technologie.",
  "Son costosos en el tiempo": "Ils coûtent cher dans la durée",
  "Mantener estas iniciativas en el tiempo tiene un alto costo lo que impide mantenerlos y tener un buen seguimiento.": "Maintenir ces initiatives dans la durée coûte cher, ce qui empêche de les pérenniser et d'assurer un bon suivi.",
  "No obtienes datos": "Tu n'obtiens pas de données",
  "No puedes medir el impacto ni el progreso de tus afiliados. Navegas a ciegas y es complicado apoyarlas correctamente.": "Tu ne peux mesurer ni l'impact ni les progrès de tes affiliés. Tu navigues à l'aveugle et il est difficile de les soutenir correctement.",
  "Solución": "Solution",
  "Diseñamos nuestra experiencia para que sea": "Nous avons conçu notre expérience pour qu'elle soit",
  "escalable al menos costo, sostenible en el tiempo y generando datos súper valiosos": "scalable au coût minimum, durable dans le temps et génératrice de données ultra précieuses",
  "Capacitación continua": "Formation continue",
  "Tenemos talleres virtuales animado por uno de nuestro experto accesible cada semana para llevarlos paso a paso..": "Des ateliers virtuels animés par l'un de nos experts, accessibles chaque semaine pour les guider pas à pas.",
  "Herramienta siempre gratuita": "Un outil gratuit pour toujours",
  "Acceden a una herramienta muy fácil de usar, que les dé resultados inmediatos, sin costo.": "Elles accèdent à un outil très simple d'utilisation, qui leur donne des résultats immédiats, sans frais.",
  "Datos increíbles y accesibles": "Des données incroyables et accessibles",
  "Entiendes el perfil de tus empresas, la manera de cómo adoptan IA y las áreas de interés que tienen.": "Tu comprends le profil de tes entreprises, leur façon d'adopter l'IA et leurs centres d'intérêt.",
  "Más que un programa: una experiencia de crecimiento empresarial": "Plus qu'un programme : une expérience de croissance entrepreneuriale",
  "Los talleres combinados con la plataforma permiten que se logre una buena adopción de la inteligencia artificial. Tus MiPyMEs se digitalizan, se vuelven más productivas y tú logras tu misión, obteniendo datos que nunca has tenido.": "Les ateliers combinés à la plateforme assurent une vraie adoption de l'intelligence artificielle. Tes TPE et PME se digitalisent, deviennent plus productives et tu accomplis ta mission, avec des données que tu n'as jamais eues.",
  "Agenda una demo y planea tu primer Taller de capacitación": "Réserve une démo et planifie ton premier atelier de formation",
  "¿Te interesa probar Logra con tu red de PyMEs?": "Envie d'essayer Logra avec ton réseau de PME ?",
  "En menos de una semana ya puedes tener resultados.": "En moins d'une semaine, tu peux déjà avoir des résultats.",
  "Hablemos de cómo impulsar la productividad y el crecimiento de tu red de PyMEs.": "Parlons de comment booster la productivité et la croissance de ton réseau de PME.",
  "Nuestro equipo quiere conversar contigo.": "Notre équipe a envie d'échanger avec toi.",
  "Agendar una llamada": "Réserver un appel",
  "IA para crecer tu PyME": "L'IA pour faire grandir ta PME",
  "En Logra, creemos en el poder de las PyMEs para transformar Latinoamérica": "Chez Logra, nous croyons au pouvoir des PME pour transformer l'Amérique latine",
  "Las PyMEs son el alma de nuestra economía, el sustento de millones de familias y el motor de nuestra región. Cuando crecen, toda la región crece.": "Les PME sont l'âme de notre économie, le soutien de millions de familles et le moteur de notre région. Quand elles grandissent, toute la région grandit.",
  "Comenzar ahora": "Commencer maintenant",
  "Hoy, 65% de las PyMEs fracasan antes de los 5 años.": "Aujourd'hui, 65% des PME échouent avant leurs 5 ans.",
  "Nuestra obsesión es cambiar eso:": "Notre obsession est de changer ça :",
  "Digitalización": "Digitalisation",
  "El 70% de las PyMEs en LatAm aún usa métodos manuales para gestionar su negocio, lo que les cuesta miles de horas en errores y reprocesos.": "70% des PME d'Amérique latine gèrent encore leur entreprise avec des méthodes manuelles, ce qui leur coûte des milliers d'heures en erreurs et reprises.",
  "Productividad": "Productivité",
  "Una PyME produce solo el 6% de lo que genera una gran empresa, debido a procesos manuales e ineficientes. Es dos veces menos que en Europa.": "Une PME produit seulement 6% de ce que génère une grande entreprise, à cause de processus manuels et inefficaces. C'est deux fois moins qu'en Europe.",
  "Datos & IA": "Données & IA",
  "Más del 90% de las PyMEs en LatAm no usan herramientas avanzadas de análisis de datos ni inteligencia artificial, navegando a ciegas para sobrevivir.": "Plus de 90% des PME d'Amérique latine n'utilisent ni outils avancés d'analyse de données ni intelligence artificielle, et naviguent à l'aveugle pour survivre.",
  "¿Cómo? Desbloqueando el potencial de cada PyME con una herramienta súper simple.": "Comment ? En débloquant le potentiel de chaque PME avec un outil ultra simple.",
  "15 años haciendo eso": "15 ans à faire ça",
  "Hemos trabajado con miles de PyMEs en toda la región, diseñando programas de productividad con bancos, gobiernos e instituciones líderes.": "Nous avons travaillé avec des milliers de PME dans toute la région, en concevant des programmes de productivité avec des banques, des gouvernements et des institutions de premier plan.",
  "Una tecnología única": "Une technologie unique",
  "Combinamos una herramienta súper simples con el poder de la inteligencia artificial, para que cada PyME mejore su productividad paso a paso.": "Nous combinons un outil ultra simple avec la puissance de l'intelligence artificielle, pour que chaque PME améliore sa productivité pas à pas.",
  "Un alianza poderosa": "Une alliance puissante",
  "Nos aliamos con entidades e instituciones que comparten nuestra visión proporcionándoles un producto que se alinea con sus objetivos estratégicos.": "Nous nous allions avec des entités et institutions qui partagent notre vision, en leur fournissant un produit aligné sur leurs objectifs stratégiques.",
  "Impactar 1 millón de PyMEs significa transformar la vida de millones de familias.": "Impacter 1 million de PME, c'est transformer la vie de millions de familles.",
  "Somos un equipo determinado y resiliente con esta pasión en común: ver a las PyMEs triunfar.": "Nous sommes une équipe déterminée et résiliente avec une passion commune : voir les PME réussir.",
  "¿Convencido?": "Convaincu ?",
  "Súmate para transformar la región a través de sus PyMEs.": "Rejoins-nous pour transformer la région à travers ses PME.",
  "Plataforma PyMES": "Plateforme PME",
  "¿Tienes una PyME? Descubre cómo puedes hacer crecer tu negocio con Logra, sin saber nada de tecnología.": "Tu as une PME ? Découvre comment faire grandir ton entreprise avec Logra, sans rien connaître à la technologie.",
  "Descubre Logra para PyMES": "Découvre Logra pour les PME",
  "Programa instituciones": "Programme institutions",
  "¿Eres parte de una institución? Explora como Logra te ayuda a impulsar el crecimiento de tu red de PyMEs, con IA.": "Tu fais partie d'une institution ? Explore comment Logra t'aide à stimuler la croissance de ton réseau de PME, avec l'IA.",
  "Explora Logra para instituciones": "Explore Logra pour les institutions",
  "Tu PyME tiene 40% más probabilidad de crecer si usas inteligencia artificial": "Ta PME a 40% de chances en plus de grandir si tu utilises l'intelligence artificielle",
  "Logra es la plataforma más simple para organizar y hacer crecer tu negocio, sin saber nada de tecnología.": "Logra est la plateforme la plus simple pour organiser et faire grandir ton entreprise, sans rien connaître à la technologie.",
  "Las razones están claras.": "Les raisons sont claires.",
  "+5h perdidas por empleado": "+5h perdues par employé",
  "Hacen tareas repetitivas e innecesarias, debido a la desorganización. Si les sobre tiempo, super. Si no, mejor hay que ahorrarlo.": "Ils font des tâches répétitives et inutiles, à cause de la désorganisation. S'il reste du temps, tant mieux. Sinon, mieux vaut l'économiser.",
  "46% no usan IA en su día día": "46% n'utilisent pas l'IA au quotidien",
  "Siguen atrapados en la ineficiencia. Más errores, más costos y menos oportunidades. Esa no es la mejor manera de crecer.": "Ils restent prisonniers de l'inefficacité. Plus d'erreurs, plus de coûts et moins d'opportunités. Ce n'est pas la meilleure façon de grandir.",
  "90% toman decisiones sin data": "90% décident sans données",
  "Toman decisiones sin analizar sus números. La intuición es buena para jugar en el casino, pero no para dirigir un negocio.": "Ils prennent des décisions sans analyser leurs chiffres. L'intuition, c'est bien pour jouer au casino, pas pour diriger une entreprise.",
  "Logra es la plataforma más simple para organizar y potencializar tu PyME, con inteligencia artificial.": "Logra est la plateforme la plus simple pour organiser et booster ta PME, avec l'intelligence artificielle.",
  "Organiza, prioriza y ejecuta tus tareas para que tu negocio sea más eficiente, productivo y rentable. ¡Sin saber nada de tecnología!": "Organise, priorise et exécute tes tâches pour rendre ton entreprise plus efficace, productive et rentable. Sans rien connaître à la technologie !",
  "Tablero": "Tableau",
  "Organiza y prioriza tus tareas para lograr más cada semana.": "Organise et priorise tes tâches pour accomplir plus chaque semaine.",
  "Mentor virtual": "Mentor virtuel",
  "Usa tu inteligencia artificial para ejecutar tareas en segundos.": "Utilise ton intelligence artificielle pour exécuter des tâches en quelques secondes.",
  "Pilares": "Piliers",
  "Construye tu estrategia clara paso a paso para tener mejor enfoque.": "Construis une stratégie claire pas à pas pour un meilleur focus.",
  "Progreso": "Progrès",
  "Visualiza tu avance cada semana y la mejora de eficiencia del equipo.": "Visualise ton avancée chaque semaine et les gains d'efficacité de l'équipe.",
  "Tablero - Tu día día en orden": "Tableau - Ton quotidien en ordre",
  "Organiza tareas, clientes y pendientes para priorizar mejor tu semana, enfocarte en lo importante y no perder más tiempo en lo innecesario.": "Organise tâches, clients et to-dos pour mieux prioriser ta semaine, te concentrer sur l'essentiel et ne plus perdre de temps sur l'inutile.",
  "Mientras que tu Mentor virtual ejecuta tareas por tí en segundos, mides la eficiencia del equipo y juntos logran más para impulsar el crecimiento del negocio.": "Pendant que ton Mentor virtuel exécute des tâches pour toi en quelques secondes, tu mesures l'efficacité de l'équipe et ensemble vous accomplissez plus pour stimuler la croissance de l'entreprise.",
  "Mentor virtual - Un negocio más eficiente": "Mentor virtuel - Une entreprise plus efficace",
  "Pregunta lo que sea y obtén respuestas 100% personalizadas para tu negocio. Tu Mentor ejecuta tareas por ti en segundos.": "Pose n'importe quelle question et obtiens des réponses 100% personnalisées pour ton entreprise. Ton Mentor exécute des tâches pour toi en quelques secondes.",
  "Desde generar contenido para redes sociales hasta estructurar entrevistas, tu Mentor entiende tu empresa y te ayuda en avanzar más rápido, con menos esfuerzo y mucho más eficiencia.": "De la création de contenu pour les réseaux sociaux à la structuration d'entretiens, ton Mentor comprend ton entreprise et t'aide à avancer plus vite, avec moins d'effort et bien plus d'efficacité.",
  "Pilares - Una estrategia clara": "Piliers - Une stratégie claire",
  "Estructura los pilares clave de tu negocio —ventas, marketing, equipo y finanzas —para que todos estén alineados y enfocados en resultados.": "Structure les piliers clés de ton entreprise — ventes, marketing, équipe et finances — pour que tout le monde soit aligné et concentré sur les résultats.",
  "Desde tu pitch de ventas hasta el perfil de tu cliente ideal, transforma tu conocimiento en formatos claros y accionables. Cada pilar completado entrena mejor a tu Mentor virtual.": "De ton pitch de vente au profil de ton client idéal, transforme tes connaissances en modèles clairs et actionnables. Chaque pilier complété entraîne mieux ton Mentor virtuel.",
  "Progreso - Decisiones más educadas": "Progrès - Des décisions plus éclairées",
  "Monitorea de tu negocio semana tras semana, visualiza los miembros del equipo más eficientes y en que área enfocan su tiempo.": "Suis ton entreprise semaine après semaine, visualise les membres de l'équipe les plus efficaces et les domaines où ils concentrent leur temps.",
  "Estos indicadores te ayudan a tener perspectiva sobre tu empresa y tener datos reales que realmente te permiten tomar mejores decisiones, dejando de navegar a ciegas.": "Ces indicateurs te donnent de la perspective sur ton entreprise et des données réelles qui te permettent vraiment de prendre de meilleures décisions, sans plus naviguer à l'aveugle.",
  "Los que adoptan inteligencia artificial crecen. Los que no, desaparecen.": "Ceux qui adoptent l'intelligence artificielle grandissent. Les autres disparaissent.",
  "¿De qué lado estarás?": "De quel côté seras-tu ?",
  "Convierte el caos en estrategia": "Transforme le chaos en stratégie",
  "Con IA puedes organizar la estrategia y las metas de cada área clave de tu negocio, para alinear a tu equipo y enfocarlo en lo que realmente importa: resultados.": "Avec l'IA, tu peux organiser la stratégie et les objectifs de chaque domaine clé de ton entreprise, pour aligner ton équipe et la concentrer sur ce qui compte vraiment : les résultats.",
  "Menos estrés, más impacto": "Moins de stress, plus d'impact",
  "La IA te puede proponer soluciones, construir planes de acción y ejecutar tareas por ti. Porque tu tiempo, y el de tu equipo, vale más que estar apagando incendios todo el día.": "L'IA peut te proposer des solutions, construire des plans d'action et exécuter des tâches pour toi. Parce que ton temps, et celui de ton équipe, vaut mieux qu'éteindre des incendies toute la journée.",
  "Decide con Datos, no con corazonadas": "Décide avec des données, pas des intuitions",
  "Puedes organizar clientes, priorizar tareas y hacer seguimiento a los indicadores para no perder oportunidades y hacer que cada paso que des, cuente.": "Tu peux organiser tes clients, prioriser tes tâches et suivre tes indicateurs pour ne pas manquer d'opportunités et faire que chaque pas compte.",
  "Plan Gratuito:": "Plan Gratuit :",
  "Limitado a 2 Miembros": "Limité à 2 membres",
  "Inteligencia artificial entrenada para tu negocio": "Intelligence artificielle entraînée pour ton entreprise",
  "Chats, tareas y tácticas ilimiatados con IA": "Chats, tâches et tactiques illimités avec l'IA",
  "Organización y seguimiento de Tareas": "Organisation et suivi des tâches",
  "Crear una cuenta": "Créer un compte",
  "Plan Pro:": "Plan Pro :",
  "Para todo tu Equipo": "Pour toute ton équipe",
  "Probar el Plan sin costo": "Essayer le plan gratuitement",
  "La Comunidad": "La communauté",
  "Conéctate y crece con nuestra comunidad de PyMEs": "Connecte-toi et grandis avec notre communauté de PME",
  "Encuentra aliados estratégicos, nuevos clientes y proveedores confiables para crecer juntos. Más conexiones, oportunidades y éxito.": "Trouve des alliés stratégiques, de nouveaux clients et des fournisseurs fiables pour grandir ensemble. Plus de connexions, d'opportunités et de succès.",
  "Crear cuenta": "Créer un compte",
  "Selecciona": "Sélectionne",
  "tu programa": "ton programme",
  "Da clic al botón de tu institución para iniciar sesión o regístrate al programa.": "Clique sur le bouton de ton institution pour te connecter ou t'inscrire au programme.",
  "Talento Pyme": "Talento Pyme",
  "MiPYME + Crecimiento": "MiPYME + Crecimiento",
  "+2000 empresarios ya se unieron": "+2000 entrepreneurs nous ont déjà rejoints",
  "IA para potenciar tu cartera de PyMEs": "L'IA pour booster ton portefeuille de PME",
  "Reduce el riesgo y aumenta la rentabilidad de tu cartera PyME": "Réduis le risque et augmente la rentabilité de ton portefeuille PME",
  "Logra es la plataforma más simple e inteligente para ayudar a tus clientes PyME a mejorar su perfil financiero.": "Logra est la plateforme la plus simple et intelligente pour aider tes clients PME à améliorer leur profil financier.",
  "65% de las PyMEs fracasan en los primeros 5 años.": "65% des PME échouent dans les 5 premières années.",
  "Cada cierre es un crédito en riesgo y una oportunidad perdida para tu Banco. ¿Las razones?": "Chaque fermeture est un crédit à risque et une opportunité perdue pour ta banque. Les raisons ?",
  "$74.3B en créditos en mora en América Latina": "$74.3B de crédits en défaut de paiement en Amérique latine",
  "La baja productividad de las PyMEs aumenta su riesgo de impago. Un costo elevado para las instituciones financieras.": "La faible productivité des PME augmente leur risque de défaut. Un coût élevé pour les institutions financières.",
  "55% de tus clientes PyME no acceden a crédito": "55% de tes clients PME n'accèdent pas au crédit",
  "Sin datos confiables ni confianza por parte de tu institución financiera, muchos quedan limitados a servicios básicos.": "Sans données fiables ni confiance de la part de ton institution financière, beaucoup restent limités aux services de base.",
  "Una oportunidad de $240B al año sin aprovechar": "Une opportunité de $240B par an inexploitée",
  "Fortalecer la productividad de tus clientes PyME puede desbloquear un enorme potencial crediticio para tu institución.": "Renforcer la productivité de tes clients PME peut débloquer un énorme potentiel de crédit pour ton institution.",
  "Logra es la plataforma más simple para fortalecer tus PyMEs con IA y optimizar la gestión de riesgo": "Logra est la plateforme la plus simple pour renforcer tes PME avec l'IA et optimiser la gestion du risque",
  "Una plataforma para que tus clientes se organicen y crezcan, integrada con un Dashboard institucional para supervisar y analizar tu cartera.": "Une plateforme pour que tes clients s'organisent et grandissent, intégrée à un dashboard institutionnel pour superviser et analyser ton portefeuille.",
  "Marca Blanca: Nuestra plataforma para PyMEs": "Marque blanche : notre plateforme pour PME",
  "Personaliza nuestra plataforma con tu identidad de marca y proporciona a tus clientes una plataforma para organizar y hacer crecer su negocio con inteligencia artificial.": "Personnalise notre plateforme avec ton identité de marque et offre à tes clients une plateforme pour organiser et faire grandir leur entreprise avec l'intelligence artificielle.",
  "Invitación clientes: Una automatización fácil": "Invitation des clients : une automatisation facile",
  "Creamos una cuenta de forma automatizada para cada cliente e invitamos a cada empresa de forma personalizada enviándoles correos y Whatsapp hasta que empiece en usar la plataforma.": "Nous créons automatiquement un compte pour chaque client et invitons chaque entreprise de façon personnalisée, par e-mails et WhatsApp, jusqu'à ce qu'elle commence à utiliser la plateforme.",
  "Análisis de datos: Un Dashboard completo": "Analyse de données : un dashboard complet",
  "En tu Dashboard, accedes a información precisa en tiempo real de tus PyMEs para ver el desempeño de tu red, detectar oportunidades y tomar decisiones que potencien tu ecosistema empresarial.": "Dans ton dashboard, tu accèdes à des informations précises en temps réel sur tes PME pour voir la performance de ton réseau, détecter des opportunités et prendre des décisions qui renforcent ton écosystème entrepreneurial.",
  "Las PyMEs que adoptan inteligencia artificial sobreviven más y pagan mejor.": "Les PME qui adoptent l'intelligence artificielle survivent plus longtemps et remboursent mieux.",
  "Aprovecha eso para ti.": "Profites-en.",
  "Reduce el riesgo": "Réduis le risque",
  "Fortalece a tus clientes PyME con una herramienta de IA que mejora su productividad y capacidad de pago.": "Renforce tes clients PME avec un outil d'IA qui améliore leur productivité et leur capacité de remboursement.",
  "Datos en tiempo real": "Données en temps réel",
  "Accede a datos precisos y actualizados para ajustar criterios de riesgo y detectar nuevas oportunidades.": "Accède à des données précises et à jour pour ajuster tes critères de risque et détecter de nouvelles opportunités.",
  "Mejora rentabilidad": "Améliore la rentabilité",
  "Aumenta la colocación de crédito identificando PyMEs con mejor desempeño mediante análisis inteligente.": "Augmente l'octroi de crédit en identifiant les PME les plus performantes grâce à une analyse intelligente.",
  "Mucho más que una plataforma: Un ecosistema de crecimiento empresarial": "Bien plus qu'une plateforme : un écosystème de croissance entrepreneuriale",
  "Convierte tu red de PyMEs en un ecosistema de colaboración y expansión. Con Logra, las empresas pueden generar nuevas oportunidades para potenciar su crecimiento. Más PyMEs creciendo, mayor impacto económico.": "Transforme ton réseau de PME en un écosystème de collaboration et d'expansion. Avec Logra, les entreprises peuvent générer de nouvelles opportunités pour stimuler leur croissance. Plus de PME qui grandissent, plus d'impact économique.",
  "Agenda una demo": "Réserve une démo",
  "Agenda una llamada para conocer Logra": "Réserve un appel pour découvrir Logra",
  "Queremos conversar sobre cómo estás mitigando el riesgo de tu cartera PyME hoy, y explorar cómo podemos apoyarte mejor.": "Nous voulons échanger sur la façon dont tu réduis aujourd'hui le risque de ton portefeuille PME, et explorer comment mieux t'accompagner.",
  "Hablemos de cómo impulsar el crecimiento de tus clientes mejora la rentabilidad de tu cartera PyME.": "Parlons de la façon dont stimuler la croissance de tes clients améliore la rentabilité de ton portefeuille PME.",
  "Impulsa el crecimiento de tus PyMEs y fortalece tu impacto.": "Stimule la croissance de tes PME et renforce ton impact.",
  "Logra es la plataforma más simple e inteligente para ayudar a tus clientes PyME a ser más productivos.": "Logra est la plateforme la plus simple et intelligente pour aider tes clients PME à être plus productifs.",
  "Cada cierre no solo afecta la economía, también destruye empleos. ¿Las razones?": "Chaque fermeture n'affecte pas seulement l'économie, elle détruit aussi des emplois. Les raisons ?",
  "El 55% de las PyMEs no accede a financiamiento": "55% des PME n'accèdent pas au financement",
  "Sin crédito ni apoyo financiero, crecer es casi imposible. Muchas quedan atrapadas en la informalidad o con procesos ineficientes que las condenan al estancamiento.": "Sans crédit ni soutien financier, grandir est presque impossible. Beaucoup restent coincées dans l'informalité ou avec des processus inefficaces qui les condamnent à la stagnation.",
  "El 70% de las PyMEs no están digitalizadas": "70% des PME ne sont pas digitalisées",
  "Siguen operando con papel, Excel y corazonadas. Sin procesos estructurados, pierden tiempo, dinero y oportunidades de financiamiento.": "Elles fonctionnent encore avec du papier, Excel et des intuitions. Sans processus structurés, elles perdent du temps, de l'argent et des opportunités de financement.",
  "Generan el 65% del empleo, pero solo aportan el 30% del PIB": "Elles génèrent 65% de l'emploi, mais ne représentent que 30% du PIB",
  "Mucho esfuerzo para poco impacto. La falta de eficiencia y profesionalización impide que las PyMEs crezcan y aporten más a la economía como en otras regiones.": "Beaucoup d'efforts pour peu d'impact. Le manque d'efficacité et de professionnalisation empêche les PME de grandir et de contribuer davantage à l'économie comme dans d'autres régions.",
  "Logra es la plataforma más simple para fortalecer tus PyMEs con IA y optimizar tu impacto económico.": "Logra est la plateforme la plus simple pour renforcer tes PME avec l'IA et optimiser ton impact économique.",
  "Una plataforma para que tus clientes se organicen y crezcan, integrada con un Dashboard institucional para supervisar y analizar el desempeño de tu red.": "Une plateforme pour que tes clients s'organisent et grandissent, intégrée à un dashboard institutionnel pour superviser et analyser la performance de ton réseau.",
  "Las PyMEs que adoptan inteligencia artificial tienen 40% más probabilidad de crecer.": "Les PME qui adoptent l'intelligence artificielle ont 40% de chances en plus de grandir.",
  "Entendimos sus retos reales": "Nous avons compris leurs vrais défis",
  "Las PyMEs apagan incendios todo el día. Necesitan apoyo en lo que realmente importa: reducir costos y aumentar ingresos.": "Les PME éteignent des incendies toute la journée. Elles ont besoin d'aide sur ce qui compte vraiment : réduire les coûts et augmenter les revenus.",
  "Creamos una herramienta muy útil": "Nous avons créé un outil très utile",
  "No tienen tiempo para aprender herramientas complejas. Diseñamos tu programa junto para que obtengan resultados rápidos.": "Elles n'ont pas le temps d'apprendre des outils complexes. Nous concevons ton programme ensemble pour qu'elles obtiennent des résultats rapides.",
  "Facilita el acceso a financiamiento": "Facilite l'accès au financement",
  "Al fortalecerlas, las estaremos preparando para acceder a mejores servicios financieros; ese es el mayor valor que puedes ofrecer.": "En les renforçant, nous les préparons à accéder à de meilleurs services financiers ; c'est la plus grande valeur que tu puisses offrir.",
  "Queremos conversar sobre cómo estás generando valor para tu red de PyMEs hoy, y explorar cómo podemos apoyarte mejor.": "Nous voulons échanger sur la façon dont tu crées de la valeur pour ton réseau de PME aujourd'hui, et explorer comment mieux t'accompagner.",
};

export const DICT_EN_PAGES: Record<string, string> = {
  "IA para potenciar tu PyME": "AI to power your SMB",
  "La inteligencia artificial creada para las MiPyMEs de Latinoamérica": "Artificial intelligence built for Latin America's micro and small businesses",
  "Logra te ayuda a ahorrar tiempo y ser más eficiente para potencializar tu negocio.": "Logra helps you save time and work more efficiently to grow your business.",
  "Probar sin costo": "Try for free",
  "4000+ MiPyMES confían en nosotros": "4000+ micro and small businesses trust us",
  "Ana Maria Ruge": "Ana Maria Ruge",
  "Efecto": "Efecto",
  "Cindy Colorado": "Cindy Colorado",
  "Dobladora y cortadora": "Dobladora y cortadora",
  "Oscar Gonzalez": "Oscar Gonzalez",
  "Inseprosas": "Inseprosas",
  "Ximena Camelo": "Ximena Camelo",
  "Mentor Go": "Mentor Go",
  "Carlos Chaves": "Carlos Chaves",
  "Datagrafía": "Datagrafía",
  "Una plataforma súper simple, hecha para empresarios que empiezan con el uso de la tecnología y quieren resultados inmediatos.": "A super simple platform, built for business owners who are just getting started with technology and want immediate results.",
  "¿Cómo Logra te da más control, más enfoque y más eficiencia en tu día a día?": "How does Logra give you more control, more focus and more efficiency every day?",
  "Ahorro de tiempo": "Time savings",
  "Ejecuta tareas en segundos en lugar de horas.": "Complete tasks in seconds instead of hours.",
  "Objetivos claros": "Clear goals",
  "Define tus metas cada semana y logra más resultados.": "Set your goals every week and achieve more.",
  "Eficiencia operativa": "Operational efficiency",
  "Construye procesos y aclara tu estrategia paso a paso.": "Build processes and clarify your strategy step by step.",
  "Progreso transparente": "Transparent progress",
  "Mide el impacto de adoptar inteligencia artificial en equipo.": "Measure the impact of adopting artificial intelligence as a team.",
  "¿Cómo funciona?": "How does it work?",
  "Chat de inteligencia artificial": "Artificial intelligence chat",
  "Conversa con tu inteligencia artificial para ejecutar tareas, tácticas o simplemente obtener apoyo, planes o ideas según tu necesidad.": "Chat with your artificial intelligence to complete tasks, run tactics or simply get support, plans or ideas whenever you need them.",
  "Organizador de Tareas": "Task Organizer",
  "Organiza tus tareas y metas en un Tablero que te permite asignar, dar seguimiento y filtrar todo lo importante de tu semana.": "Organize your tasks and goals on a Board that lets you assign, track and filter everything that matters in your week.",
  "Formatos para tu Estrategia": "Templates for your Strategy",
  "Entrena a tu inteligencia artificial con formatos inteligentes para que conozca a tu empresa mejor que cualquier Asesor y te de respuestas súper personalizadas.": "Train your artificial intelligence with smart templates so it knows your business better than any advisor and gives you highly personalized answers.",
  "Progreso semanal": "Weekly progress",
  "Mide las tareas que completas y el uso de inteligencia artificial de tu equipo para entender el tiempo ahorrado y la eficiencia de tu equipo.": "Measure completed tasks and your team's use of artificial intelligence to understand time saved and team efficiency.",
  "Urgencia": "Urgency",
  "2 de cada 3 PyMEs fracasan en los primeros 5 años.": "2 out of 3 SMBs fail within the first 5 years.",
  "¿De qué lado quieres estar?": "Which side do you want to be on?",
  "+5h pérdidas por empleado cada semana": "+5h lost per employee every week",
  "Hacen tareas repetitivas e innecesarias, por ser desorganizados. Si les sobre tiempo, super. Si no, mejor ahórralo.": "They do repetitive, unnecessary tasks caused by disorganization. If you have time to spare, great. If not, better save it.",
  "+70% siguen operando en papel y Excel": "+70% still run on paper and Excel",
  "La ineficiencia y falta de digitalización les cuesta. Más errores, más costos y menos oportunidades: la peor manera de crecer.": "Inefficiency and lack of digitalization cost them. More errors, higher costs and fewer opportunities: the worst way to grow.",
  "90% toman decisiones con emociones y sin data": "90% make decisions on emotions, without data",
  "Decidir sin analizar números es muy arriesgado. La intuición es buena para jugar en el casino, pero no para dirigir un negocio.": "Deciding without analyzing your numbers is very risky. Intuition is fine for the casino, not for running a business.",
  "Beneficios": "Benefits",
  "Las MiPyMEs que adoptan inteligencia artificial": "Micro and small businesses that adopt artificial intelligence",
  "tienen": "are",
  "40% más probabilidad de crecer.": "40% more likely to grow.",
  "La IA trabaja por ti": "AI works for you",
  "Enfócate en lo importante": "Focus on what matters",
  "Decides con más seguridad": "Decide with more confidence",
  "La inteligencia artificial trabaja por ti": "Artificial intelligence works for you",
  "Ejecuta tus tareas repetitivas en segundos. Te crea planes de acción y procesos para avanzar más rápido.": "It handles your repetitive tasks in seconds. It creates action plans and processes so you move faster.",
  "Nuestros Planes": "Our Plans",
  "Diseñado para crecer en Equipo.": "Designed to grow as a team.",
  "Plan Básico": "Basic Plan",
  "Micro Empresarios": "Micro business owners",
  "$9 USD/mes": "$9 USD/mo",
  "Inteligencia artificial 100% personalizada a tu negocio": "Artificial intelligence 100% personalized to your business",
  "20 Chats, tareas y tácticas con IA": "20 AI chats, tasks and tactics",
  "Organización y seguimiento de Tareas cada semana": "Task organization and tracking every week",
  "Plan Pro": "Pro Plan",
  "Equipo de 3": "Team of 3",
  "$14 USD/mes": "$14 USD/mo",
  "Todo lo incluido en el Plan Gratuito": "Everything in the Free Plan",
  "Acceso a 2 miembros de tu equipo": "Access for 2 team members",
  "Chats, tareas y tácticas con IA ilimitados": "Unlimited AI chats, tasks and tactics",
  "Plan Premium": "Premium Plan",
  "Todo tu equipo": "Your whole team",
  "$25 USD/mes": "$25 USD/mo",
  "Todo lo incluido en el Plan Pro": "Everything in the Pro Plan",
  "Miembros de equipo ilimitado": "Unlimited team members",
  "Asesoría de 30 minutos y soporte prioritario": "30-minute advisory session and priority support",
  "Oportunidad": "Opportunity",
  "4000+ empresarios ya usan Logra para mejorar cada día": "4000+ business owners already use Logra to improve every day",
  "Pruébalo sin costo hoy y obtén resultados de inmediato.": "Try it for free today and get results right away.",
  "Crea una cuenta": "Create an account",
  "IA para potenciar tu red de PyMEs": "AI to power your SMB network",
  "Capacita tus MiPyMEs y dales acceso a la inteligencia artificial": "Train your micro and small businesses and give them access to artificial intelligence",
  "Logra es una solución llave en mano que impulsa a tus afiliados y te da acceso a datos increíbles para entenderlos mejor.": "Logra is a turnkey solution that empowers your members and gives you access to incredible data to understand them better.",
  "Agenda una Demo": "Book a Demo",
  "Trabajamos con instituciones líderes en Colombia y nuestro servicio está disponible en toda América Latina.": "We work with leading institutions in Colombia and our service is available across Latin America.",
  "Cómo funciona": "How it works",
  "Combinamos Talleres virtuales, una plataforma 100% hecha para MiPyMEs de la región y un Dashboard de datos para tu institución.": "We combine virtual workshops, a platform built 100% for the region's micro and small businesses, and a data dashboard for your institution.",
  "Diseñamos una experiencia completa que te permite apoyar la mayor cantidad de negocios afiliados de tu red, al menor costo posible.": "We designed a complete experience that lets you support as many member businesses in your network as possible, at the lowest possible cost.",
  "Talleres virtuales de capacitación": "Virtual training workshops",
  "Son sesiones de 60 minutos que llevamos cada semana para guiar a las PyMEs a empezar a utilizar la inteligencia artificial para organizar sus tareas, ejecutarlas en segundos y medir el tiempo ahorrado.": "60-minute sessions we run every week to guide SMBs as they start using artificial intelligence to organize their tasks, complete them in seconds and measure the time saved.",
  "Análisis de datos en tiempo real": "Real-time data analysis",
  "Accedes a un Dashboard analítico que te permite analizar datos de todas tus MiPyMEs afiliadas que utilizan la plataforma. Entiendes mejor sus retos y cómo usan la IA, para diseñar soluciones más adecuadas.": "You get an analytics dashboard to analyze data from all your member businesses using the platform. You better understand their challenges and how they use AI, so you can design better-fitting solutions.",
  "Modelo ganar/ganar para todos": "A win-win model for everyone",
  "Por ser invitadas por ti, tus empresas afiliadas acceden a la versión gratuita de forma permanente. Si contratan la versión Pro, les damos un descuento por ser de tu red y a ti te entregamos un porcentaje.": "Because you invite them, your member businesses get the free version permanently. If they upgrade to Pro, they get a discount for being part of your network and you receive a percentage.",
  "Los programas e iniciativas de apoyo que despliegan para apoyar a sus MiPyMEs": "The support programs and initiatives rolled out for their micro and small businesses",
  "tienen ciertos limitantes.": "have certain limitations.",
  "No son escalables": "They don't scale",
  "Los cursos, asesorías y talleres están limitados a pocas empresas. El impacto es limitado por falta de tecnología.": "Courses, advisory and workshops reach only a few businesses. Impact is limited by the lack of technology.",
  "Son costosos en el tiempo": "They're costly over time",
  "Mantener estas iniciativas en el tiempo tiene un alto costo lo que impide mantenerlos y tener un buen seguimiento.": "Sustaining these initiatives over time is expensive, which makes them hard to maintain and follow up on properly.",
  "No obtienes datos": "You don't get data",
  "No puedes medir el impacto ni el progreso de tus afiliados. Navegas a ciegas y es complicado apoyarlas correctamente.": "You can't measure your members' impact or progress. You're flying blind, and supporting them properly is hard.",
  "Solución": "Solution",
  "Diseñamos nuestra experiencia para que sea": "We designed our experience to be",
  "escalable al menos costo, sostenible en el tiempo y generando datos súper valiosos": "scalable at minimal cost, sustainable over time and generating incredibly valuable data",
  "Capacitación continua": "Continuous training",
  "Tenemos talleres virtuales animado por uno de nuestro experto accesible cada semana para llevarlos paso a paso..": "Virtual workshops led by one of our experts, available every week to guide them step by step.",
  "Herramienta siempre gratuita": "An always-free tool",
  "Acceden a una herramienta muy fácil de usar, que les dé resultados inmediatos, sin costo.": "They get a very easy-to-use tool that delivers immediate results, at no cost.",
  "Datos increíbles y accesibles": "Incredible, accessible data",
  "Entiendes el perfil de tus empresas, la manera de cómo adoptan IA y las áreas de interés que tienen.": "You understand your businesses' profiles, how they adopt AI and their areas of interest.",
  "Más que un programa: una experiencia de crecimiento empresarial": "More than a program: a business growth experience",
  "Los talleres combinados con la plataforma permiten que se logre una buena adopción de la inteligencia artificial. Tus MiPyMEs se digitalizan, se vuelven más productivas y tú logras tu misión, obteniendo datos que nunca has tenido.": "Workshops combined with the platform drive real adoption of artificial intelligence. Your micro and small businesses go digital, become more productive, and you fulfill your mission with data you've never had before.",
  "Agenda una demo y planea tu primer Taller de capacitación": "Book a demo and plan your first training workshop",
  "¿Te interesa probar Logra con tu red de PyMEs?": "Interested in trying Logra with your SMB network?",
  "En menos de una semana ya puedes tener resultados.": "You can see results in less than a week.",
  "Hablemos de cómo impulsar la productividad y el crecimiento de tu red de PyMEs.": "Let's talk about boosting the productivity and growth of your SMB network.",
  "Nuestro equipo quiere conversar contigo.": "Our team wants to talk with you.",
  "Agendar una llamada": "Schedule a call",
  "IA para crecer tu PyME": "AI to grow your SMB",
  "En Logra, creemos en el poder de las PyMEs para transformar Latinoamérica": "At Logra, we believe in the power of SMBs to transform Latin America",
  "Las PyMEs son el alma de nuestra economía, el sustento de millones de familias y el motor de nuestra región. Cuando crecen, toda la región crece.": "SMBs are the soul of our economy, the livelihood of millions of families and the engine of our region. When they grow, the whole region grows.",
  "Comenzar ahora": "Start now",
  "Hoy, 65% de las PyMEs fracasan antes de los 5 años.": "Today, 65% of SMBs fail before their fifth year.",
  "Nuestra obsesión es cambiar eso:": "Our obsession is to change that:",
  "Digitalización": "Digitalization",
  "El 70% de las PyMEs en LatAm aún usa métodos manuales para gestionar su negocio, lo que les cuesta miles de horas en errores y reprocesos.": "70% of SMBs in LatAm still manage their business with manual methods, costing them thousands of hours in errors and rework.",
  "Productividad": "Productivity",
  "Una PyME produce solo el 6% de lo que genera una gran empresa, debido a procesos manuales e ineficientes. Es dos veces menos que en Europa.": "An SMB produces only 6% of what a large company generates, due to manual, inefficient processes. That's half the level seen in Europe.",
  "Datos & IA": "Data & AI",
  "Más del 90% de las PyMEs en LatAm no usan herramientas avanzadas de análisis de datos ni inteligencia artificial, navegando a ciegas para sobrevivir.": "Over 90% of SMBs in LatAm use no advanced data analytics or artificial intelligence, flying blind to survive.",
  "¿Cómo? Desbloqueando el potencial de cada PyME con una herramienta súper simple.": "How? By unlocking each SMB's potential with a super simple tool.",
  "15 años haciendo eso": "15 years doing this",
  "Hemos trabajado con miles de PyMEs en toda la región, diseñando programas de productividad con bancos, gobiernos e instituciones líderes.": "We've worked with thousands of SMBs across the region, designing productivity programs with banks, governments and leading institutions.",
  "Una tecnología única": "A unique technology",
  "Combinamos una herramienta súper simples con el poder de la inteligencia artificial, para que cada PyME mejore su productividad paso a paso.": "We combine a super simple tool with the power of artificial intelligence, so every SMB improves its productivity step by step.",
  "Un alianza poderosa": "A powerful alliance",
  "Nos aliamos con entidades e instituciones que comparten nuestra visión proporcionándoles un producto que se alinea con sus objetivos estratégicos.": "We partner with entities and institutions that share our vision, providing them a product aligned with their strategic goals.",
  "Impactar 1 millón de PyMEs significa transformar la vida de millones de familias.": "Impacting 1 million SMBs means transforming the lives of millions of families.",
  "Somos un equipo determinado y resiliente con esta pasión en común: ver a las PyMEs triunfar.": "We're a determined, resilient team with one shared passion: seeing SMBs succeed.",
  "¿Convencido?": "Convinced?",
  "Súmate para transformar la región a través de sus PyMEs.": "Join us to transform the region through its SMBs.",
  "Plataforma PyMES": "SMB Platform",
  "¿Tienes una PyME? Descubre cómo puedes hacer crecer tu negocio con Logra, sin saber nada de tecnología.": "Do you run an SMB? Discover how to grow your business with Logra, no tech knowledge needed.",
  "Descubre Logra para PyMES": "Discover Logra for SMBs",
  "Programa instituciones": "Institutions program",
  "¿Eres parte de una institución? Explora como Logra te ayuda a impulsar el crecimiento de tu red de PyMEs, con IA.": "Part of an institution? Explore how Logra helps you drive the growth of your SMB network with AI.",
  "Explora Logra para instituciones": "Explore Logra for institutions",
  "Tu PyME tiene 40% más probabilidad de crecer si usas inteligencia artificial": "Your SMB is 40% more likely to grow if you use artificial intelligence",
  "Logra es la plataforma más simple para organizar y hacer crecer tu negocio, sin saber nada de tecnología.": "Logra is the simplest platform to organize and grow your business, no tech knowledge needed.",
  "Las razones están claras.": "The reasons are clear.",
  "+5h perdidas por empleado": "+5h lost per employee",
  "Hacen tareas repetitivas e innecesarias, debido a la desorganización. Si les sobre tiempo, super. Si no, mejor hay que ahorrarlo.": "They do repetitive, unnecessary tasks due to disorganization. If there's time to spare, great. If not, better to save it.",
  "46% no usan IA en su día día": "46% don't use AI in their daily work",
  "Siguen atrapados en la ineficiencia. Más errores, más costos y menos oportunidades. Esa no es la mejor manera de crecer.": "They stay trapped in inefficiency. More errors, higher costs and fewer opportunities. That's not the best way to grow.",
  "90% toman decisiones sin data": "90% make decisions without data",
  "Toman decisiones sin analizar sus números. La intuición es buena para jugar en el casino, pero no para dirigir un negocio.": "They make decisions without analyzing their numbers. Intuition is fine for the casino, not for running a business.",
  "Logra es la plataforma más simple para organizar y potencializar tu PyME, con inteligencia artificial.": "Logra is the simplest platform to organize and power up your SMB with artificial intelligence.",
  "Organiza, prioriza y ejecuta tus tareas para que tu negocio sea más eficiente, productivo y rentable. ¡Sin saber nada de tecnología!": "Organize, prioritize and complete your tasks to make your business more efficient, productive and profitable. No tech knowledge needed!",
  "Tablero": "Board",
  "Organiza y prioriza tus tareas para lograr más cada semana.": "Organize and prioritize your tasks to achieve more every week.",
  "Mentor virtual": "Virtual Mentor",
  "Usa tu inteligencia artificial para ejecutar tareas en segundos.": "Use your artificial intelligence to complete tasks in seconds.",
  "Pilares": "Pillars",
  "Construye tu estrategia clara paso a paso para tener mejor enfoque.": "Build a clear strategy step by step for better focus.",
  "Progreso": "Progress",
  "Visualiza tu avance cada semana y la mejora de eficiencia del equipo.": "See your progress every week and your team's efficiency gains.",
  "Tablero - Tu día día en orden": "Board - Your day-to-day in order",
  "Organiza tareas, clientes y pendientes para priorizar mejor tu semana, enfocarte en lo importante y no perder más tiempo en lo innecesario.": "Organize tasks, clients and to-dos to better prioritize your week, focus on what matters and stop wasting time on the unnecessary.",
  "Mientras que tu Mentor virtual ejecuta tareas por tí en segundos, mides la eficiencia del equipo y juntos logran más para impulsar el crecimiento del negocio.": "While your Virtual Mentor completes tasks for you in seconds, you measure your team's efficiency and together you achieve more to drive business growth.",
  "Mentor virtual - Un negocio más eficiente": "Virtual Mentor - A more efficient business",
  "Pregunta lo que sea y obtén respuestas 100% personalizadas para tu negocio. Tu Mentor ejecuta tareas por ti en segundos.": "Ask anything and get answers 100% personalized to your business. Your Mentor completes tasks for you in seconds.",
  "Desde generar contenido para redes sociales hasta estructurar entrevistas, tu Mentor entiende tu empresa y te ayuda en avanzar más rápido, con menos esfuerzo y mucho más eficiencia.": "From generating social media content to structuring interviews, your Mentor understands your company and helps you move faster, with less effort and far more efficiency.",
  "Pilares - Una estrategia clara": "Pillars - A clear strategy",
  "Estructura los pilares clave de tu negocio —ventas, marketing, equipo y finanzas —para que todos estén alineados y enfocados en resultados.": "Structure your business's key pillars — sales, marketing, team and finance — so everyone is aligned and focused on results.",
  "Desde tu pitch de ventas hasta el perfil de tu cliente ideal, transforma tu conocimiento en formatos claros y accionables. Cada pilar completado entrena mejor a tu Mentor virtual.": "From your sales pitch to your ideal customer profile, turn your knowledge into clear, actionable templates. Every completed pillar trains your Virtual Mentor better.",
  "Progreso - Decisiones más educadas": "Progress - More informed decisions",
  "Monitorea de tu negocio semana tras semana, visualiza los miembros del equipo más eficientes y en que área enfocan su tiempo.": "Monitor your business week after week, see which team members are most efficient and where they focus their time.",
  "Estos indicadores te ayudan a tener perspectiva sobre tu empresa y tener datos reales que realmente te permiten tomar mejores decisiones, dejando de navegar a ciegas.": "These indicators give you perspective on your company and real data that truly lets you make better decisions, no more flying blind.",
  "Los que adoptan inteligencia artificial crecen. Los que no, desaparecen.": "Those who adopt artificial intelligence grow. Those who don't, disappear.",
  "¿De qué lado estarás?": "Which side will you be on?",
  "Convierte el caos en estrategia": "Turn chaos into strategy",
  "Con IA puedes organizar la estrategia y las metas de cada área clave de tu negocio, para alinear a tu equipo y enfocarlo en lo que realmente importa: resultados.": "With AI you can organize the strategy and goals of every key area of your business, aligning your team and focusing it on what really matters: results.",
  "Menos estrés, más impacto": "Less stress, more impact",
  "La IA te puede proponer soluciones, construir planes de acción y ejecutar tareas por ti. Porque tu tiempo, y el de tu equipo, vale más que estar apagando incendios todo el día.": "AI can suggest solutions, build action plans and complete tasks for you. Because your time, and your team's, is worth more than putting out fires all day.",
  "Decide con Datos, no con corazonadas": "Decide with data, not gut feelings",
  "Puedes organizar clientes, priorizar tareas y hacer seguimiento a los indicadores para no perder oportunidades y hacer que cada paso que des, cuente.": "You can organize clients, prioritize tasks and track your indicators so you never miss opportunities and every step you take counts.",
  "Plan Gratuito:": "Free Plan:",
  "Limitado a 2 Miembros": "Limited to 2 members",
  "Inteligencia artificial entrenada para tu negocio": "Artificial intelligence trained for your business",
  "Chats, tareas y tácticas ilimiatados con IA": "Unlimited AI chats, tasks and tactics",
  "Organización y seguimiento de Tareas": "Task organization and tracking",
  "Crear una cuenta": "Create an account",
  "Plan Pro:": "Pro Plan:",
  "Para todo tu Equipo": "For your whole team",
  "Probar el Plan sin costo": "Try the plan for free",
  "La Comunidad": "The Community",
  "Conéctate y crece con nuestra comunidad de PyMEs": "Connect and grow with our SMB community",
  "Encuentra aliados estratégicos, nuevos clientes y proveedores confiables para crecer juntos. Más conexiones, oportunidades y éxito.": "Find strategic allies, new clients and reliable suppliers to grow together. More connections, opportunities and success.",
  "Crear cuenta": "Create account",
  "Selecciona": "Select",
  "tu programa": "your program",
  "Da clic al botón de tu institución para iniciar sesión o regístrate al programa.": "Click your institution's button to log in or sign up for the program.",
  "Talento Pyme": "Talento Pyme",
  "MiPYME + Crecimiento": "MiPYME + Crecimiento",
  "+2000 empresarios ya se unieron": "+2000 business owners have already joined",
  "IA para potenciar tu cartera de PyMEs": "AI to power your SMB portfolio",
  "Reduce el riesgo y aumenta la rentabilidad de tu cartera PyME": "Reduce risk and increase the profitability of your SMB portfolio",
  "Logra es la plataforma más simple e inteligente para ayudar a tus clientes PyME a mejorar su perfil financiero.": "Logra is the simplest, smartest platform to help your SMB clients improve their financial profile.",
  "65% de las PyMEs fracasan en los primeros 5 años.": "65% of SMBs fail within the first 5 years.",
  "Cada cierre es un crédito en riesgo y una oportunidad perdida para tu Banco. ¿Las razones?": "Every closure is a loan at risk and a missed opportunity for your bank. The reasons?",
  "$74.3B en créditos en mora en América Latina": "$74.3B in non-performing loans in Latin America",
  "La baja productividad de las PyMEs aumenta su riesgo de impago. Un costo elevado para las instituciones financieras.": "SMBs' low productivity increases their risk of default. A high cost for financial institutions.",
  "55% de tus clientes PyME no acceden a crédito": "55% of your SMB clients can't access credit",
  "Sin datos confiables ni confianza por parte de tu institución financiera, muchos quedan limitados a servicios básicos.": "Without reliable data or your financial institution's trust, many remain limited to basic services.",
  "Una oportunidad de $240B al año sin aprovechar": "A $240B-a-year opportunity left untapped",
  "Fortalecer la productividad de tus clientes PyME puede desbloquear un enorme potencial crediticio para tu institución.": "Strengthening your SMB clients' productivity can unlock enormous credit potential for your institution.",
  "Logra es la plataforma más simple para fortalecer tus PyMEs con IA y optimizar la gestión de riesgo": "Logra is the simplest platform to strengthen your SMBs with AI and optimize risk management",
  "Una plataforma para que tus clientes se organicen y crezcan, integrada con un Dashboard institucional para supervisar y analizar tu cartera.": "A platform for your clients to get organized and grow, integrated with an institutional dashboard to monitor and analyze your portfolio.",
  "Marca Blanca: Nuestra plataforma para PyMEs": "White label: Our SMB platform",
  "Personaliza nuestra plataforma con tu identidad de marca y proporciona a tus clientes una plataforma para organizar y hacer crecer su negocio con inteligencia artificial.": "Customize our platform with your brand identity and give your clients a platform to organize and grow their business with artificial intelligence.",
  "Invitación clientes: Una automatización fácil": "Client invitations: Easy automation",
  "Creamos una cuenta de forma automatizada para cada cliente e invitamos a cada empresa de forma personalizada enviándoles correos y Whatsapp hasta que empiece en usar la plataforma.": "We automatically create an account for each client and invite every business personally, via email and WhatsApp, until they start using the platform.",
  "Análisis de datos: Un Dashboard completo": "Data analysis: A complete dashboard",
  "En tu Dashboard, accedes a información precisa en tiempo real de tus PyMEs para ver el desempeño de tu red, detectar oportunidades y tomar decisiones que potencien tu ecosistema empresarial.": "In your dashboard, you access precise real-time information on your SMBs to see your network's performance, spot opportunities and make decisions that strengthen your business ecosystem.",
  "Las PyMEs que adoptan inteligencia artificial sobreviven más y pagan mejor.": "SMBs that adopt artificial intelligence survive longer and repay better.",
  "Aprovecha eso para ti.": "Make that work for you.",
  "Reduce el riesgo": "Reduce risk",
  "Fortalece a tus clientes PyME con una herramienta de IA que mejora su productividad y capacidad de pago.": "Strengthen your SMB clients with an AI tool that improves their productivity and ability to pay.",
  "Datos en tiempo real": "Real-time data",
  "Accede a datos precisos y actualizados para ajustar criterios de riesgo y detectar nuevas oportunidades.": "Access precise, up-to-date data to adjust risk criteria and spot new opportunities.",
  "Mejora rentabilidad": "Improve profitability",
  "Aumenta la colocación de crédito identificando PyMEs con mejor desempeño mediante análisis inteligente.": "Increase loan origination by identifying top-performing SMBs through smart analysis.",
  "Mucho más que una plataforma: Un ecosistema de crecimiento empresarial": "Much more than a platform: A business growth ecosystem",
  "Convierte tu red de PyMEs en un ecosistema de colaboración y expansión. Con Logra, las empresas pueden generar nuevas oportunidades para potenciar su crecimiento. Más PyMEs creciendo, mayor impacto económico.": "Turn your SMB network into an ecosystem of collaboration and expansion. With Logra, businesses can generate new opportunities to fuel their growth. More SMBs growing, greater economic impact.",
  "Agenda una demo": "Book a demo",
  "Agenda una llamada para conocer Logra": "Schedule a call to get to know Logra",
  "Queremos conversar sobre cómo estás mitigando el riesgo de tu cartera PyME hoy, y explorar cómo podemos apoyarte mejor.": "We want to talk about how you're mitigating your SMB portfolio's risk today, and explore how we can better support you.",
  "Hablemos de cómo impulsar el crecimiento de tus clientes mejora la rentabilidad de tu cartera PyME.": "Let's talk about how driving your clients' growth improves your SMB portfolio's profitability.",
  "Impulsa el crecimiento de tus PyMEs y fortalece tu impacto.": "Drive your SMBs' growth and strengthen your impact.",
  "Logra es la plataforma más simple e inteligente para ayudar a tus clientes PyME a ser más productivos.": "Logra is the simplest, smartest platform to help your SMB clients become more productive.",
  "Cada cierre no solo afecta la economía, también destruye empleos. ¿Las razones?": "Every closure doesn't just hurt the economy, it also destroys jobs. The reasons?",
  "El 55% de las PyMEs no accede a financiamiento": "55% of SMBs can't access financing",
  "Sin crédito ni apoyo financiero, crecer es casi imposible. Muchas quedan atrapadas en la informalidad o con procesos ineficientes que las condenan al estancamiento.": "Without credit or financial support, growing is nearly impossible. Many stay trapped in informality or with inefficient processes that doom them to stagnation.",
  "El 70% de las PyMEs no están digitalizadas": "70% of SMBs aren't digitalized",
  "Siguen operando con papel, Excel y corazonadas. Sin procesos estructurados, pierden tiempo, dinero y oportunidades de financiamiento.": "They still run on paper, Excel and gut feelings. Without structured processes, they lose time, money and financing opportunities.",
  "Generan el 65% del empleo, pero solo aportan el 30% del PIB": "They generate 65% of employment but contribute only 30% of GDP",
  "Mucho esfuerzo para poco impacto. La falta de eficiencia y profesionalización impide que las PyMEs crezcan y aporten más a la economía como en otras regiones.": "A lot of effort for little impact. The lack of efficiency and professionalization keeps SMBs from growing and contributing more to the economy, as they do in other regions.",
  "Logra es la plataforma más simple para fortalecer tus PyMEs con IA y optimizar tu impacto económico.": "Logra is the simplest platform to strengthen your SMBs with AI and optimize your economic impact.",
  "Una plataforma para que tus clientes se organicen y crezcan, integrada con un Dashboard institucional para supervisar y analizar el desempeño de tu red.": "A platform for your clients to get organized and grow, integrated with an institutional dashboard to monitor and analyze your network's performance.",
  "Las PyMEs que adoptan inteligencia artificial tienen 40% más probabilidad de crecer.": "SMBs that adopt artificial intelligence are 40% more likely to grow.",
  "Entendimos sus retos reales": "We understood their real challenges",
  "Las PyMEs apagan incendios todo el día. Necesitan apoyo en lo que realmente importa: reducir costos y aumentar ingresos.": "SMBs put out fires all day. They need support with what really matters: cutting costs and increasing revenue.",
  "Creamos una herramienta muy útil": "We built a truly useful tool",
  "No tienen tiempo para aprender herramientas complejas. Diseñamos tu programa junto para que obtengan resultados rápidos.": "They don't have time to learn complex tools. We design your program together so they get quick results.",
  "Facilita el acceso a financiamiento": "Ease access to financing",
  "Al fortalecerlas, las estaremos preparando para acceder a mejores servicios financieros; ese es el mayor valor que puedes ofrecer.": "By strengthening them, we prepare them to access better financial services; that's the greatest value you can offer.",
  "Queremos conversar sobre cómo estás generando valor para tu red de PyMEs hoy, y explorar cómo podemos apoyarte mejor.": "We want to talk about how you're creating value for your SMB network today, and explore how we can better support you.",
};
