export const DICT_FR_CORE: Record<string, string> = {
  "Logra": "Logra",
  "Micro y pequeñas empresas": "Micro et petites entreprises",
  "Cámaras e Instituciones": "Chambres et institutions",
  "Nosotros": "À propos",
  "ES": "FR",
  "Español": "Español",
  "Français": "Français",
  "English": "English",
  "Iniciar sesión": "Se connecter",
  "Crear Cuenta": "Créer un compte",
  "Ver demo": "Voir la démo",
  "Tu PyME crece más rápido con inteligencia artificial": "Ta PME grandit plus vite avec l'intelligence artificielle",
  "Ahorra tiempo, organiza tu semana y toma mejores decisiones. Crea tu cuenta gratis y empieza a ver resultados desde el primer día.": "Gagne du temps, organise ta semaine et prends de meilleures décisions. Crée ton compte gratuit et commence à voir des résultats dès le premier jour.",
  "Crear mi cuenta gratis": "Créer mon compte gratuit",
  "Plataforma para micro y pequeñas empresas": "Plateforme pour micro et petites entreprises",
  "Programa de productividad para Instituciones": "Programme de productivité pour les institutions",
  "Sobre Nosotros": "À propos de nous",
  "DigitizeMe Inc. 2025 © Todos los derechos reservados.": "DigitizeMe Inc. 2025 © Tous droits réservés.",
  "Aviso de Privacidad": "Politique de confidentialité",
  "Términos y Condiciones": "Conditions générales",
  "Problema": "Problème",
};

export const DICT_EN_CORE: Record<string, string> = {
  "Logra": "Logra",
  "Micro y pequeñas empresas": "Micro and small businesses",
  "Cámaras e Instituciones": "Chambers and Institutions",
  "Nosotros": "About us",
  "ES": "EN",
  "Español": "Español",
  "Français": "Français",
  "English": "English",
  "Iniciar sesión": "Log in",
  "Crear Cuenta": "Create Account",
  "Ver demo": "View demo",
  "Tu PyME crece más rápido con inteligencia artificial": "Your SMB grows faster with artificial intelligence",
  "Ahorra tiempo, organiza tu semana y toma mejores decisiones. Crea tu cuenta gratis y empieza a ver resultados desde el primer día.": "Save time, organize your week and make better decisions. Create your free account and start seeing results from day one.",
  "Crear mi cuenta gratis": "Create my free account",
  "Plataforma para micro y pequeñas empresas": "Platform for micro and small businesses",
  "Programa de productividad para Instituciones": "Productivity program for institutions",
  "Sobre Nosotros": "About us",
  "DigitizeMe Inc. 2025 © Todos los derechos reservados.": "DigitizeMe Inc. 2025 © All rights reserved.",
  "Aviso de Privacidad": "Privacy Policy",
  "Términos y Condiciones": "Terms and Conditions",
  "Problema": "Problem",
};
